In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn import datasets
iris = datasets.load_iris()

In [4]:
print('iris 키:', iris.keys())

iris 키: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [5]:
print('데이터:\n', iris['data'][:5])

데이터:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [8]:
print('특성 이름:', iris['feature_names'])

특성 이름: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [9]:
print('타깃:\n', iris['target'][:5])

타깃:
 [0 0 0 0 0]


In [10]:
print('타깃 이름:', iris['target_names'])

타깃 이름: ['setosa' 'versicolor' 'virginica']


In [11]:
print('데이터 크기:', iris['data'].shape)
print('타깃 크기:', iris['target'].shape)

데이터 크기: (150, 4)
타깃 크기: (150,)


In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris['data'], iris['target'], random_state=0)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(112, 4) (112,)
(38, 4) (38,)


In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3) #n_neighbors = 이웃개수 

In [20]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [22]:
import numpy as np

X_new = np.array([[6, 3.5, 5, 1.5]])

In [24]:
pred = knn.predict(X_new)
print(pred)
print(iris['target_names'][pred])

[1]
['versicolor']


In [28]:
y_pred = knn.predict(X_test)
print('테스트세트 예측값:\n', y_pred) #정답예측 (실제와 다를 수 있음)
print('테스트세트 실제타깃:\n', y_test) #실제정답

테스트세트 예측값:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
테스트세트 실제타깃:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]


In [32]:
print(f'훈련 세트 정확도: {knn.score(X_train, y_train):.3f}')
print(f'테스트 세트 정확도: {knn.score(X_test, y_test):.3f}') #.3f는 소수점 3자리까지

훈련 세트 정확도: 0.964
테스트 세트 정확도: 0.974


In [34]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

#데이터 수집하기
wine = datasets.load_wine()
print('wine 키:', wine.keys())
print('데이터:\n', wine['data'][:5])
print('특성이름:', wine['feature_names'])
print('타깃:\n', wine['target'][:5])
print('타깃이름:', wine['target_names'])
print('데이터 크기:', wine['data'].shape)
print('타깃 크기:', wine['data'].shape)

wine 키: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])
데이터:
 [[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]
특성이름: ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
타깃:
 [0 0 0 0

In [36]:
#데이터 전처리
X_train, X_test, y_train, y_test = train_test_split(wine['data'], wine['target'], random_state=0)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(133, 13) (133,)
(45, 13) (45,)


In [38]:
#모델 생성하기
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [40]:
#모델 이용해서 예측하기
y_pred = knn.predict(X_test)
print('테스트세트 예측값:\n', y_pred)
print('테스트세트 실제타깃:\n', y_test)

테스트세트 예측값:
 [0 1 1 0 1 1 0 1 1 1 0 1 0 2 0 1 0 0 1 0 1 0 1 1 0 1 1 1 2 2 0 0 1 0 0 0 0
 1 1 0 2 0 1 1 1]
테스트세트 실제타깃:
 [0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


In [41]:
#모델 평가하기
print(f'훈련 세트 정확도: {knn.score(X_train, y_train):.3f}')
print(f'테스트 세트 정확도: {knn.score(X_test, y_test):.3f}')

훈련 세트 정확도: 0.887
테스트 세트 정확도: 0.733
